// src/components/client/ClientLoyalty.vue
<template>
  <div class="loyalty-container">
    <div v-if="client">
      <div class="loyalty-header">
        <div class="loyalty-level" :class="client.loyalty_level">
          <h2>Niveau {{ getLevelName(client.loyalty_level) }}</h2>
          <div class="loyalty-points">
            <span class="points">{{ client.loyalty_points }}</span>
            <span class="points-label">points</span>
          </div>
        </div>
      </div>

      <div class="loyalty-benefits">
        <h3>Avantages du niveau {{ getLevelName(client.loyalty_level) }}</h3>
        <ul>
          <li v-for="(benefit, index) in levelBenefits.benefits" :key="index">
            {{ benefit }}
          </li>
        </ul>
      </div>

      <div class="loyalty-progress">
        <h3>Progression</h3>
        <div class="progress-container">
          <div class="progress-bar">
            <div class="progress-level standard" :class="{ active: client.loyalty_level === 'standard' }">Standard</div>
            <div class="progress-level silver" :class="{ active: client.loyalty_level === 'silver' }">Silver</div>
            <div class="progress-level gold" :class="{ active: client.loyalty_level === 'gold' }">Gold</div>
            <div class="progress-level platinum" :class="{ active: client.loyalty_level === 'platinum' }">Platinum</div>
          </div>
          <div class="progress-info">
            <div v-if="client.loyalty_level !== 'platinum'">
              <p>{{ getNextLevelPoints(client.loyalty_level) - client.loyalty_points }} points supplémentaires pour atteindre le niveau {{ getNextLevelName(client.loyalty_level) }}</p>
            </div>
            <div v-else>
              <p>Félicitations ! Vous avez atteint le niveau maximum.</p>
            </div>
          </div>
        </div>
      </div>

      <div class="loyalty-actions">
        <div class="action-section">
          <h3>Ajouter des points</h3>
          <div class="action-form">
            <div class="form-group">
              <label for="add-points">Points</label>
              <input type="number" id="add-points" v-model="addPoints" min="1" />
            </div>
            <div class="form-group">
              <label for="add-description">Description</label>
              <input type="text" id="add-description" v-model="addDescription" placeholder="Raison de l'ajout" />
            </div>
            <button @click="handleAddPoints" :disabled="!addPoints || addPoints <= 0" class="btn btn-primary">
              Ajouter
            </button>
          </div>
        </div>

        <div class="action-section">
          <h3>Utiliser des points</h3>
          <div class="action-form">
            <div class="form-group">
              <label for="redeem-points">Points</label>
              <input type="number" id="redeem-points" v-model="redeemPoints" min="1" :max="client.loyalty_points" />
            </div>
            <div class="form-group">
              <label for="redeem-description">Description</label>
              <input type="text" id="redeem-description" v-model="redeemDescription" placeholder="Raison de l'utilisation" />
            </div>
            <button @click="handleRedeemPoints" :disabled="!redeemPoints || redeemPoints <= 0 || redeemPoints > client.loyalty_points" class="btn btn-primary">
              Utiliser
            </button>
          </div>
        </div>
      </div>

      <div class="loyalty-history">
        <h3>Historique des points</h3>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Date</th>
              <th>Type</th>
              <th>Points</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(item, index) in sortedHistory" :key="index" :class="getHistoryItemClass(item)">
              <td>{{ formatDate(item.date) }}</td>
              <td>{{ getHistoryTypeLabel(item.type) }}</td>
              <td>{{ item.points_change > 0 ? '+' + item.points_change : item.points_change }}</td>
              <td>{{ item.description }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div v-else class="no-client">
      <p>Veuillez sélectionner un client pour voir son programme de fidélité.</p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed, PropType } from 'vue';
import { Client, LoyaltyHistoryItem, clientService } from '@/services/clientService';

export default defineComponent({
  name: 'ClientLoyalty',
  props: {
    client: {
      type: Object as PropType<Client>,
      required: true
    }
  },
  setup(props) {
    const addPoints = ref<number>(null);
    const addDescription = ref('');
    const redeemPoints = ref<number>(null);
    const redeemDescription = ref('');

    const levelBenefits = computed(() => {
      if (!props.client) return { discount: 0, benefits: [] };
      return clientService.getLoyaltyLevelBenefits(props.client.loyalty_level);
    });

    const sortedHistory = computed(() => {
      if (!props.client || !props.client.loyalty_history) return [];
      return [...props.client.loyalty_history].sort((a, b) => {
        return new Date(b.date).getTime() - new Date(a.date).getTime();
      });
    });

    const handleAddPoints = async () => {
      if (!props.client || !addPoints.value || addPoints.value <= 0) return;
      
      try {
        await clientService.addLoyaltyPoints(
          props.client.id,
          addPoints.value,
          addDescription.value || 'Ajout manuel de points'
        );
        
        // Réinitialiser les champs
        addPoints.value = null;
        addDescription.value = '';
      } catch (error) {
        console.error('Erreur lors de l\'ajout de points:', error);
      }
    };

    const handleRedeemPoints = async () => {
      if (!props.client || !redeemPoints.value || redeemPoints.value <= 0 || redeemPoints.value > props.client.loyalty_points) return;
      
      try {
        await clientService.redeemLoyaltyPoints(
          props.client.id,
          redeemPoints.value,
          redeemDescription.value || 'Utilisation manuelle de points'
        );
        
        // Réinitialiser les champs
        redeemPoints.value = null;
        redeemDescription.value = '';
      } catch (error) {
        console.error('Erreur lors de l\'utilisation de points:', error);
      }
    };

    const getLevelName = (level: string): string => {
      switch (level) {
        case 'standard': return 'Standard';
        case 'silver': return 'Silver';
        case 'gold': return 'Gold';
        case 'platinum': return 'Platinum';
        default: return 'Standard';
      }
    };

    const getNextLevelName = (level: string): string => {
      switch (level) {
        case 'standard': return 'Silver';
        case 'silver': return 'Gold';
        case 'gold': return 'Platinum';
        default: return '';
      }
    };

    const getNextLevelPoints = (level: string): number => {
      switch (level) {
        case 'standard': return 200; // Points pour Silver
        case 'silver': return 400;   // Points pour Gold
        case 'gold': return 750;     // Points pour Platinum
        default: return 0;
      }
    };

    const getHistoryTypeLabel = (type: string): string => {
      switch (type) {
        case 'earn': return 'Gain';
        case 'redeem': return 'Utilisation';
        case 'level_change': return 'Changement de niveau';
        default: return type;
      }
    };

    const getHistoryItemClass = (item: LoyaltyHistoryItem): string => {
      switch (item.type) {
        case 'earn': return 'history-earn';
        case 'redeem': return 'history-redeem';
        case 'level_change': return 'history-level';
        default: return '';
      }
    };

    const formatDate = (dateString: string): string => {
      const date = new Date(dateString);
      return date.toLocaleDateString('fr-FR', {
        day: '2-digit',
        month: '2-digit',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      });
    };

    return {
      addPoints,
      addDescription,
      redeemPoints,
      redeemDescription,
      levelBenefits,
      sortedHistory,
      handleAddPoints,
      handleRedeemPoints,
      getLevelName,
      getNextLevelName,
      getNextLevelPoints,
      getHistoryTypeLabel,
      getHistoryItemClass,
      formatDate
    };
  }
});
</script>

<style scoped>
.loyalty-container {
  padding: 20px;
}

.loyalty-header {
  display: flex;
  justify-content: center;
  margin-bottom: 30px;
}

.loyalty-level {
  text-align: center;
  padding: 20px;
  border-radius: 10px;
  width: 300px;
  color: white;
}

.loyalty-level.standard {
  background-color: #6c757d;
}

.loyalty-level.silver {
  background-color: #adb5bd;
}

.loyalty-level.gold {
  background-color: #ffc107;
  color: #212529;
}

.loyalty-level.platinum {
  background-color: #17a2b8;
}

.loyalty-points {
  margin-top: 10px;
}

.points {
  font-size: 2.5rem;
  font-weight: bold;
}

.points-label {
  font-size: 1.2rem;
  margin-left: 5px;
}

.loyalty-benefits {
  margin-bottom: 30px;
  padding: 15px;
  background-color: #f8f9fa;
  border-radius: 5px;
}

.loyalty-benefits ul {
  list-style-type: none;
  padding-left: 0;
}

.loyalty-benefits li {
  padding: 8px 0;
  border-bottom: 1px solid #e9ecef;
}

.loyalty-benefits li:last-child {
  border-bottom: none;
}

.loyalty-progress {
  margin-bottom: 30px;
}

.progress-container {
  background-color: #f8f9fa;
  padding: 15px;
  border-radius: 5px;
}

.progress-bar {
  display: flex;
  justify-content: space-between;
  margin-bottom: 15px;
}

.progress-level {
  padding: 10px;
  border-radius: 5px;
  text-align: center;
  flex-grow: 1;
  margin: 0 5px;
  opacity: 0.5;
}

.progress-level.active {
  opacity: 1;
  font-weight: bold;
}

.progress-level.standard {
  background-color: #6c757d;
  color: white;
}

.progress-level.silver {
  background-color: #adb5bd;
  color: white;
}

.progress-level.gold {
  background-color: #ffc107;
  color: #212529;
}

.progress-level.platinum {
  background-color: #17a2b8;
  color: white;
}

.progress-info {
  text-align: center;
  font-weight: bold;
}

.loyalty-actions {
  display: flex;
  justify-content: space-between;
  margin-bottom: 30px;
}

.action-section {
  width: 48%;
  background-color: #f8f9fa;
  padding: 15px;
  border-radius: 5px;
}

.action-form {
  margin-top: 15px;
}

.form-group {
  margin-bottom: 15px;
}

.form-group label {
  display: block;
  margin-bottom: 5px;
}

.form-group input {
  width: 100%;
  padding: 8px;
  border: 1px solid #ced4da;
  border-radius: 4px;
}

.btn {
  padding: 8px 16px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.btn-primary {
  background-color: #007bff;
  color: white;
}

.btn-primary:hover {
  background-color: #0069d9;
}

.btn-primary:disabled {
  background-color: #6c757d;
  cursor: not-allowed;
}

.loyalty-history {
  margin-top: 30px;
}

.table {
  width: 100%;
  border-collapse: collapse;
}

.table th, .table td {
  padding: 10px;
  text-align: left;
  border-bottom: 1px solid #dee2e6;
}

.table th {
  background-color: #f8f9fa;
}

.table-striped tbody tr:nth-of-type(odd) {
  background-color: rgba(0, 0, 0, 0.05);
}

.history-earn {
  color: #28a745;
}

.history-redeem {
  color: #dc3545;
}

.history-level {
  color: #17a2b8;
  font-weight: bold;
}

.no-client {
  text-align: center;
  padding: 50px;
  background-color: #f8f9fa;
  border-radius: 5px;
}
</style>

// src/components/clients/ClientLoyalty.tsx
import React, { useState, useEffect } from 'react';
import { Client, clientService } from '../../services/clientService';

interface ClientLoyaltyProps {
  client: Client;
}

const ClientLoyalty: React.FC<ClientLoyaltyProps> = ({ client }) => {
  const [addPoints, setAddPoints] = useState<number | null>(null);
  const [addDescription, setAddDescription] = useState('');
  const [redeemPoints, setRedeemPoints] = useState<number | null>(null);
  const [redeemDescription, setRedeemDescription] = useState('');
  const [levelBenefits, setLevelBenefits] = useState<{ discount: number, benefits: string[] }>({ discount: 0, benefits: [] });

  useEffect(() => {
    if (client) {
      setLevelBenefits(clientService.getLoyaltyLevelBenefits(client.loyalty_level));
    }
  }, [client]);

  const handleAddPoints = async () => {
    if (!client || !addPoints || addPoints <= 0) return;
    
    try {
      await clientService.addLoyaltyPoints(
        client.id,
        addPoints,
        addDescription || 'Ajout manuel de points'
      );
      
      // Réinitialiser les champs
      setAddPoints(null);
      setAddDescription('');
    } catch (error) {
      console.error('Erreur lors de l\'ajout de points:', error);
    }
  };

  const handleRedeemPoints = async () => {
    if (!client || !redeemPoints || redeemPoints <= 0 || redeemPoints > client.loyalty_points) return;
    
    try {
      await clientService.redeemLoyaltyPoints(
        client.id,
        redeemPoints,
        redeemDescription || 'Utilisation manuelle de points'
      );
      
      // Réinitialiser les champs
      setRedeemPoints(null);
      setRedeemDescription('');
    } catch (error) {
      console.error('Erreur lors de l\'utilisation de points:', error);
    }
  };

  const getLevelName = (level: string): string => {
    switch (level) {
      case 'standard': return 'Standard';
      case 'silver': return 'Silver';
      case 'gold': return 'Gold';
      case 'platinum': return 'Platinum';
      default: return 'Standard';
    }
  };

  const getNextLevelName = (level: string): string => {
    switch (level) {
      case 'standard': return 'Silver';
      case 'silver': return 'Gold';
      case 'gold': return 'Platinum';
      default: return '';
    }
  };

  const getNextLevelPoints = (level: string): number => {
    switch (level) {
      case 'standard': return 200; // Points pour Silver
      case 'silver': return 400;   // Points pour Gold
      case 'gold': return 750;     // Points pour Platinum
      default: return 0;
    }
  };

  const getHistoryTypeLabel = (type: string): string => {
    switch (type) {
      case 'earn': return 'Gain';
      case 'redeem': return 'Utilisation';
      case 'level_change': return 'Changement de niveau';
      default: return type;
    }
  };

  const getHistoryItemClass = (type: string): string => {
    switch (type) {
      case 'earn': return 'text-green-600';
      case 'redeem': return 'text-red-600';
      case 'level_change': return 'text-blue-600 font-bold';
      default: return '';
    }
  };

  const formatDate = (dateString: string): string => {
    const date = new Date(dateString);
    return date.toLocaleDateString('fr-FR', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const sortedHistory = [...(client.loyalty_history || [])].sort((a, b) => {
    return new Date(b.date).getTime() - new Date(a.date).getTime();
  });

  return (
    <div className="bg-white p-6 rounded-lg shadow">
      <h2 className="text-xl font-semibold mb-4">Programme de Fidélité</h2>

      <div className={`mb-6 p-4 rounded-lg text-white ${
        client.loyalty_level === 'standard' ? 'bg-gray-600' :
        client.loyalty_level === 'silver' ? 'bg-gray-400' :
        client.loyalty_level === 'gold' ? 'bg-yellow-500' : 'bg-blue-500'
      }`}>
        <div className="flex justify-between items-center">
          <h3 className="text-lg font-semibold">Niveau {getLevelName(client.loyalty_level)}</h3>
          <div className="text-center">
            <span className="text-3xl font-bold">{client.loyalty_points}</span>
            <span className="ml-1">points</span>
          </div>
        </div>
      </div>

      <div className="mb-6 p-4 bg-gray-50 rounded-lg">
        <h3 className="font-semibold mb-2">Avantages du niveau {getLevelName(client.loyalty_level)}</h3>
        <ul className="list-disc pl-5">
          {levelBenefits.benefits.map((benefit, index) => (
            <li key={index} className="py-1">{benefit}</li>
          ))}
        </ul>
      </div>

      <div className="mb-6">
        <h3 className="font-semibold mb-2">Progression</h3>
        <div className="p-4 bg-gray-50 rounded-lg">
          <div className="flex justify-between mb-4">
            <div className={`px-3 py-2 rounded ${client.loyalty_level === 'standard' ? 'bg-gray-600 text-white font-bold' : 'bg-gray-300'}`}>Standard</div>
            <div className={`px-3 py-2 rounded ${client.loyalty_level === 'silver' ? 'bg-gray-400 text-white font-bold' : 'bg-gray-300'}`}>Silver</div>
            <div className={`px-3 py-2 rounded ${client.loyalty_level === 'gold' ? 'bg-yellow-500 text-black font-bold' : 'bg-gray-300'}`}>Gold</div>
            <div className={`px-3 py-2 rounded ${client.loyalty_level === 'platinum' ? 'bg-blue-500 text-white font-bold' : 'bg-gray-300'}`}>Platinum</div>
          </div>
          {client.loyalty_level !== 'platinum' ? (
            <p className="text-center font-semibold">
              {getNextLevelPoints(client.loyalty_level) - client.loyalty_points} points supplémentaires pour atteindre le niveau {getNextLevelName(client.loyalty_level)}
            </p>
          ) : (
            <p className="text-center font-semibold text-green-600">
              Félicitations ! Vous avez atteint le niveau maximum.
            </p>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
        <div className="p-4 bg-gray-50 rounded-lg">
          <h3 className="font-semibold mb-2">Ajouter des points</h3>
          <div className="mb-2">
            <label htmlFor="add-points" className="block text-gray-700 mb-1">Points</label>
            <input
              type="number"
              id="add-points"
              value={addPoints || ''}
              onChange={(e) => setAddPoints(parseInt(e.target.value) || null)}
              min="1"
              className="w-full p-2 border rounded"
            />
          </div>
          <div className="mb-2">
            <label htmlFor="add-description" className="block text-gray-700 mb-1">Description</label>
            <input
              type="text"
              id="add-description"
              value={addDescription}
              onChange={(e) => setAddDescription(e.target.value)}
              placeholder="Raison de l'ajout"
              className="w-full p-2 border rounded"
            />
          </div>
          <button
            onClick={handleAddPoints}
            disabled={!addPoints || addPoints <= 0}
            className="w-full px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 disabled:bg-gray-400"
          >
            Ajouter
          </button>
        </div>

        <div className="p-4 bg-gray-50 rounded-lg">
          <h3 className="font-semibold mb-2">Utiliser des points</h3>
          <div className="mb-2">
            <label htmlFor="redeem-points" className="block text-gray-700 mb-1">Points</label>
            <input
              type="number"
              id="redeem-points"
              value={redeemPoints || ''}
              onChange={(e) => setRedeemPoints(parseInt(e.target.value) || null)}
              min="1"
              max={client.loyalty_points}
              className="w-full p-2 border rounded"
            />
          </div>
          <div className="mb-2">
            <label htmlFor="redeem-description" className="block text-gray-700 mb-1">Description</label>
            <input
              type="text"
              id="redeem-description"
              value={redeemDescription}
              onChange={(e) => setRedeemDescription(e.target.value)}
              placeholder="Raison de l'utilisation"
              className="w-full p-2 border rounded"
            />
          </div>
          <button
            onClick={handleRedeemPoints}
            disabled={!redeemPoints || redeemPoints <= 0 || redeemPoints > client.loyalty_points}
            className="w-full px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 disabled:bg-gray-400"
          >
            Utiliser
          </button>
        </div>
      </div>

      <div>
        <h3 className="font-semibold mb-2">Historique des points</h3>
        <div className="overflow-x-auto">
          <table className="min-w-full bg-white">
            <thead>
              <tr className="bg-gray-100">
                <th className="py-2 px-4 text-left">Date</th>
                <th className="py-2 px-4 text-left">Type</th>
                <th className="py-2 px-4 text-left">Points</th>
                <th className="py-2 px-4 text-left">Description</th>
              </tr>
            </thead>
            <tbody>
              {sortedHistory.map((item, index) => (
                <tr key={index} className={`border-t ${index % 2 === 0 ? 'bg-gray-50' : ''}`}>
                  <td className="py-2 px-4">{formatDate(item.date)}</td>
                  <td className="py-2 px-4">{getHistoryTypeLabel(item.type)}</td>
                  <td className={`py-2 px-4 ${getHistoryItemClass(item.type)}`}>
                    {item.points_change > 0 ? '+' + item.points_change : item.points_change}
                  </td>
                  <td className="py-2 px-4">{item.description}</td>
                </tr>
              ))}
              {sortedHistory.length === 0 && (
                <tr>
                  <td colSpan={4} className="py-4 text-center text-gray-500">
                    Aucun historique disponible
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default ClientLoyalty;
